fix: fix version incompatibility between pylint-django and astroid
When running pylint, the following error occurs, "ImportError: cannot import name 'scoped_nodes' from 'astroid.nodes' (/home/runner/work/super-csv/super-csv/.tox/quality/lib/python3.8/site-packages/astroid/nodes.py)".

This is due to a conflict between the versions of astroid==2.6.6 and pylint-django==2.5.0.

pylint-django==2.5.0 includes a change to the way modules from the astroid library are imported. In particular, "from astroid import MANAGER, AstroidImportError, inference_tip, nodes, scoped_nodes" changed to "astroid.nodes import scoped_nodes". It doesn't appear that pylint-django lists its dependencies, but the pull request references the following

"astroid.scoped_nodes is deprecated and will be moved to astroid.nodes.scoped_nodes in astroid 3.0 - see https://github.com/PyCQA/astroid/blob/main/astroid/scoped_nodes.py#L26

However it seems like the release of 2.9.1 moved some members already, so this PR just uses the new locations."

The 2.5.0 version of pylint-django assumes astroid>=2.9.1 is installed. However, we have an older version of astroid installed that has not yet moved the nodes module, hence the error, as our version of pylint-django expects the moved module.

The older version of astroid comes from pylint and pylint-celery. Our version of pylint is 2.7.4. We have a constraint pylint<2.8` with the comment "version 2.8 introduced breaking changes that have not yet been resolved, can be removed when version 2.8.2 is released". pylint is on version 2.12.2, so we have passed the threshold for removing this constraint.